# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eth2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\neth2.proto\x12\x02v1\"\x93\x01\n\x0f\x41ttestationData\x12\x0c\n\x04slot\x18\x01 \x01(\x04\x12\x17\n\x0f\x63ommittee_index\x18\x02 \x01(\x04\x12\x19\n\x11\x62\x65\x61\x63on_block_root\x18\x03 \x01(\x0c\x12\x1e\n\x06source\x18\x04 \x01(\x0b\x32\x0e.v1.Checkpoint\x12\x1e\n\x06target\x18\x05 \x01(\x0b\x32\x0e.v1.Checkpoint\")\n\nCheckpoint\x12\r\n\x05\x65poch\x18\x01 \x01(\x04\x12\x0c\n\x04root\x18\x02 \x01(\x0c\"u\n\x11\x42\x65\x61\x63onBlockHeader\x12\x0c\n\x04slot\x18\x01 \x01(\x04\x12\x16\n\x0eproposer_index\x18\x02 \x01(\x04\x12\x13\n\x0bparent_root\x18\x03 \x01(\x0c\x12\x12\n\nstate_root\x18\x04 \x01(\x0c\x12\x11\n\tbody_root\x18\x05 \x01(\x0c\x42y\n\x1e\x63om.wealdtech.eth2signerapi.v1B\tEth2ProtoP\x01Z*github.com/wealdtech/eth2-signer-api/pb/v1\xaa\x02\rEth2Signer.v1\xca\x02\rEth2Signer\\v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eth2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.wealdtech.eth2signerapi.v1B\tEth2ProtoP\001Z*github.com/wealdtech/eth2-signer-api/pb/v1\252\002\rEth2Signer.v1\312\002\rEth2Signer\\v1'
  _ATTESTATIONDATA._serialized_start=19
  _ATTESTATIONDATA._serialized_end=166
  _CHECKPOINT._serialized_start=168
  _CHECKPOINT._serialized_end=209
  _BEACONBLOCKHEADER._serialized_start=211
  _BEACONBLOCKHEADER._serialized_end=328
# @@protoc_insertion_point(module_scope)
