# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: endpoint.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65ndpoint.proto\x12\x02v1\"2\n\x08\x45ndpoint\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\rB}\n\x1e\x63om.wealdtech.eth2signerapi.v1B\rEndpointProtoP\x01Z*github.com/wealdtech/eth2-signer-api/pb/v1\xaa\x02\rEth2Signer.v1\xca\x02\rEth2Signer\\v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpoint_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.wealdtech.eth2signerapi.v1B\rEndpointProtoP\001Z*github.com/wealdtech/eth2-signer-api/pb/v1\252\002\rEth2Signer.v1\312\002\rEth2Signer\\v1'
  _ENDPOINT._serialized_start=22
  _ENDPOINT._serialized_end=72
# @@protoc_insertion_point(module_scope)
