# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: responsestate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13responsestate.proto\x12\x02v1*C\n\rResponseState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tSUCCEEDED\x10\x01\x12\n\n\x06\x44\x45NIED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x42\x82\x01\n\x1e\x63om.wealdtech.eth2signerapi.v1B\x12ResponseStateProtoP\x01Z*github.com/wealdtech/eth2-signer-api/pb/v1\xaa\x02\rEth2Signer.v1\xca\x02\rEth2Signer\\v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responsestate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.wealdtech.eth2signerapi.v1B\022ResponseStateProtoP\001Z*github.com/wealdtech/eth2-signer-api/pb/v1\252\002\rEth2Signer.v1\312\002\rEth2Signer\\v1'
  _RESPONSESTATE._serialized_start=27
  _RESPONSESTATE._serialized_end=94
# @@protoc_insertion_point(module_scope)
